export function generateCode(project) {
  const hardwareNames = {
    leftFront: 'left_front',
    rightFront: 'right_front',
    leftBack: 'left_back',
    rightBack: 'right_back',
    liftMotor: 'lift_motor',
    intakeServo: 'intake_servo',
  };
  return {
    'Constants.java': `package org.firstinspires.ftc.teamcode;\n\npublic final class Constants {\n    public static final double DRIVE_LIMIT = 0.70;\n    public static final double TURN_LIMIT = 0.65;\n    public static final int LIFT_LOW_TICKS = 450;\n    public static final int LIFT_HIGH_TICKS = 1050;\n    public static final double INTAKE_OPEN = 0.78;\n    public static final double INTAKE_CLOSED = 0.18;\n    private Constants() {}\n}\n`,
    'RobotHardware.java': `package org.firstinspires.ftc.teamcode;\n\nimport com.qualcomm.robotcore.hardware.DcMotor;\nimport com.qualcomm.robotcore.hardware.HardwareMap;\nimport com.qualcomm.robotcore.hardware.Servo;\n\npublic class RobotHardware {\n    public DcMotor leftFront, rightFront, leftBack, rightBack, liftMotor;\n    public Servo intakeServo;\n    public DriveSubsystem drive;\n    public LiftSubsystem lift;\n\n    public void init(HardwareMap hardwareMap) {\n        leftFront = hardwareMap.get(DcMotor.class, "${hardwareNames.leftFront}");\n        rightFront = hardwareMap.get(DcMotor.class, "${hardwareNames.rightFront}");\n        leftBack = hardwareMap.get(DcMotor.class, "${hardwareNames.leftBack}");\n        rightBack = hardwareMap.get(DcMotor.class, "${hardwareNames.rightBack}");\n        liftMotor = hardwareMap.get(DcMotor.class, "${hardwareNames.liftMotor}");\n        intakeServo = hardwareMap.get(Servo.class, "${hardwareNames.intakeServo}");\n\n        rightFront.setDirection(DcMotor.Direction.REVERSE);\n        rightBack.setDirection(DcMotor.Direction.REVERSE);\n        liftMotor.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);\n        drive = new DriveSubsystem(leftFront, rightFront, leftBack, rightBack);\n        lift = new LiftSubsystem(liftMotor);\n    }\n}\n`,
    'DriveSubsystem.java': `package org.firstinspires.ftc.teamcode;\n\nimport com.qualcomm.robotcore.hardware.DcMotor;\nimport com.qualcomm.robotcore.util.Range;\n\npublic class DriveSubsystem {\n    private final DcMotor leftFront, rightFront, leftBack, rightBack;\n\n    public DriveSubsystem(DcMotor leftFront, DcMotor rightFront, DcMotor leftBack, DcMotor rightBack) {\n        this.leftFront = leftFront;\n        this.rightFront = rightFront;\n        this.leftBack = leftBack;\n        this.rightBack = rightBack;\n    }\n\n    public void mecanum(double y, double x, double turn) {\n        double lf = y + x + turn;\n        double rf = y - x - turn;\n        double lb = y - x + turn;\n        double rb = y + x - turn;\n        double max = Math.max(1.0, Math.max(Math.abs(lf), Math.max(Math.abs(rf), Math.max(Math.abs(lb), Math.abs(rb)))));\n        leftFront.setPower(Range.clip(lf / max, -Constants.DRIVE_LIMIT, Constants.DRIVE_LIMIT));\n        rightFront.setPower(Range.clip(rf / max, -Constants.DRIVE_LIMIT, Constants.DRIVE_LIMIT));\n        leftBack.setPower(Range.clip(lb / max, -Constants.DRIVE_LIMIT, Constants.DRIVE_LIMIT));\n        rightBack.setPower(Range.clip(rb / max, -Constants.DRIVE_LIMIT, Constants.DRIVE_LIMIT));\n    }\n\n    public void stop() { mecanum(0, 0, 0); }\n}\n`,
    'LiftSubsystem.java': `package org.firstinspires.ftc.teamcode;\n\nimport com.qualcomm.robotcore.hardware.DcMotor;\nimport com.qualcomm.robotcore.util.Range;\n\npublic class LiftSubsystem {\n    private final DcMotor liftMotor;\n\n    public LiftSubsystem(DcMotor liftMotor) {\n        this.liftMotor = liftMotor;\n        this.liftMotor.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);\n        this.liftMotor.setMode(DcMotor.RunMode.RUN_USING_ENCODER);\n    }\n\n    public void manual(double stick) {\n        liftMotor.setPower(Range.clip(-stick, -0.55, 0.75));\n    }\n\n    public void goTo(int ticks) {\n        liftMotor.setTargetPosition(ticks);\n        liftMotor.setMode(DcMotor.RunMode.RUN_TO_POSITION);\n        liftMotor.setPower(0.65);\n    }\n}\n`,
    'TeleOpMain.java': `package org.firstinspires.ftc.teamcode;\n\nimport com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;\nimport com.qualcomm.robotcore.eventloop.opmode.TeleOp;\n\n@TeleOp(name = "Blueprint TeleOp")\npublic class TeleOpMain extends LinearOpMode {\n    private final RobotHardware robot = new RobotHardware();\n\n    @Override\n    public void runOpMode() {\n        robot.init(hardwareMap);\n        telemetry.addLine("Hardware initialized. Config names are case-sensitive.");\n        telemetry.update();\n        waitForStart();\n\n        while (opModeIsActive()) {\n            double slow = gamepad1.left_bumper ? 0.42 : 1.0;\n            robot.drive.mecanum(-gamepad1.left_stick_y * slow, gamepad1.left_stick_x * slow, gamepad1.right_stick_x * slow);\n            robot.lift.manual(gamepad2.left_stick_y);\n            if (gamepad2.a) robot.intakeServo.setPosition(Constants.INTAKE_CLOSED);\n            if (gamepad2.b) robot.intakeServo.setPosition(Constants.INTAKE_OPEN);\n            telemetry.addData("slowMode", gamepad1.left_bumper);\n            telemetry.update();\n        }\n    }\n}\n`,
    'AutoMain.java': `package org.firstinspires.ftc.teamcode;\n\nimport com.qualcomm.robotcore.eventloop.opmode.Autonomous;\nimport com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;\n\n@Autonomous(name = "Blueprint Auto")\npublic class AutoMain extends LinearOpMode {\n    private final RobotHardware robot = new RobotHardware();\n\n    @Override\n    public void runOpMode() throws InterruptedException {\n        robot.init(hardwareMap);\n        telemetry.addLine("Tune wheel diameter, gear ratio, track width, and battery assumptions before competition.");\n        telemetry.update();\n        waitForStart();\n\n        robot.drive.mecanum(0.35, 0, 0);\n        sleep(750);\n        robot.drive.stop();\n        robot.lift.goTo(Constants.LIFT_LOW_TICKS);\n        sleep(900);\n        robot.intakeServo.setPosition(Constants.INTAKE_OPEN);\n        sleep(250);\n        robot.drive.stop();\n    }\n}\n`,
    'README.md': `# Blueprint Starter Code\n\nGenerated for ${project.team.name}. Confirm FTC SDK version, package path, hardware names, motor direction, encoder constants, and legal behavior before competition.\n\nHardware configuration names:\n${Object.values(hardwareNames).map((name) => `- ${name}`).join('\n')}\n`,
  };
}
